name: game
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  html_unescape: ^0.1.5
  json_object: ^1.0.19
  logging: ^0.11.3+1

dev_dependencies:
  test: ^0.12.0
